export const ACTIVITIES = "ACTIVITIES"
export const ORDER = "ORDER"
export const ALLCOUNTRIES = "ALLCOUNTRIES"
export const PAGED = "PAGED"
export const SEARCH = "SEARCH"
export const NEWACTIVITIES = "NEWACTIVITIES"
export const CLEARFILTERS = "CLEARFILTERS"
export const FILTERS = "FILTERS"